name: GAS Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Decode secrets and write .clasprc.json
        run: |
          echo "${{ secrets.CLASP_CREDENTIALS_BASE64 }}" | base64 --decode > ~/.clasprc.json

      - name: Push to GAS
        run: clasp push
